services:
  db:
    image: postgres:latest
    container_name: pandora_db
    environment:
      POSTGRES_DB: pandora_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_pass
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    container_name: pandora_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    container_name: pandora_web
    environment:
      DEBUG: True
      SECRET_KEY: v0v8JHJuM8OzY2
      DATABASE_NAME: pandora_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: secret_pass
      DATABASE_HOST: pandora_db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MEDIA_ROOT: "/app/uploads" # mesma pasta que o volume
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; while !</dev/tcp/redis/6379; do sleep 1; done; python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - uploads_data:/app/uploads # pasta de uploads compartilhada
    stdin_open: true
    tty: true
    ports:
      - "${WEB_PORT:-8085}:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    container_name: pandora_celery_worker
    environment:
      DEBUG: True
      SECRET_KEY: v0v8JHJuM8OzY2
      DATABASE_NAME: pandora_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: secret_pass
      DATABASE_HOST: pandora_db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MEDIA_ROOT: "/app/uploads" # mesma pasta que o volume
    command: celery -A citosharp worker -l info
    volumes:
      - uploads_data:/app/uploads # compartilha os uploads com web
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD-SHELL", "celery -A citosharp inspect ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  pgdata:
  redis_data:
  uploads_data:
networks:
  pandora_net:
    driver: bridge
    external: true
