services:
  db:
    image: postgres:16
    container_name: pandora_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pandora_net

  pandora_web:
    image: "${DOCKER_USER}/pandora-backend:${IMAGE_TAG:-latest}"
    container_name: pandora_web
    command: bash -c "python manage.py migrate && gunicorn citosharp.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads
    environment:
      DEBUG: "${DEBUG}"
      SECRET_KEY: "${SECRET_KEY}"
      ALLOWED_HOSTS: api.project-pandora.com.br,localhost,127.0.0.1
      DATABASE_NAME: "${POSTGRES_DB}"
      DATABASE_USER: "${POSTGRES_USER}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      MEDIA_ROOT: "/app/uploads"
    networks:
      - pandora_net

volumes:
  pgdata:
  uploads_data:

networks:
  pandora_net:
    driver: bridge
    external: true
