# Generated by Django 5.0.2 on 2024-03-20 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExperimentModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "experiment",
            },
        ),
        migrations.CreateModel(
            name="FileDataModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("headers", models.JSONField()),
                ("data_set", models.JSONField()),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fcs_parser.experimentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "file_data",
            },
        ),
    ]
