# Generated by Django 5.1.3 on 2025-01-29 10:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExperimentModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(max_length=100, null=True)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                ("error_info", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "experiment",
            },
        ),
        migrations.CreateModel(
            name="FileModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=256, null=True)),
                ("file", models.FileField(null=True, upload_to="storage")),
                (
                    "experiment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fcs_parser.experimentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "experiment_files",
            },
        ),
        migrations.CreateModel(
            name="FileDataModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=256, null=True)),
                ("headers", models.JSONField()),
                ("data_set", models.JSONField()),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fcs_parser.experimentmodel",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_data",
                        to="fcs_parser.filemodel",
                    ),
                ),
            ],
            options={
                "db_table": "file_data",
            },
        ),
        migrations.CreateModel(
            name="GateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("x_min", models.FloatField()),
                ("x_max", models.FloatField()),
                ("y_min", models.FloatField()),
                ("y_max", models.FloatField()),
                ("x_axis", models.CharField(max_length=50)),
                ("y_axis", models.CharField(max_length=50)),
                ("data_set", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates",
                        to="fcs_parser.experimentmodel",
                    ),
                ),
                (
                    "file_data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates",
                        to="fcs_parser.filedatamodel",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="fcs_parser.gatemodel",
                    ),
                ),
            ],
            options={
                "db_table": "gate",
            },
        ),
    ]
