# Generated by Django 5.2.1 on 2025-10-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemodel",
            name="file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
