# Generated by Django 5.1.3 on 2025-03-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gatemodel",
            name="x_axis",
        ),
        migrations.RemoveField(
            model_name="gatemodel",
            name="x_max",
        ),
        migrations.RemoveField(
            model_name="gatemodel",
            name="x_min",
        ),
        migrations.RemoveField(
            model_name="gatemodel",
            name="y_axis",
        ),
        migrations.RemoveField(
            model_name="gatemodel",
            name="y_max",
        ),
        migrations.RemoveField(
            model_name="gatemodel",
            name="y_min",
        ),
        migrations.AddField(
            model_name="gatemodel",
            name="gate_coordinates",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
