# Generated by Django 5.0.2 on 2024-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedatamodel",
            name="file_name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
