# Generated by Django 5.2.1 on 2025-11-07 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0002_alter_filemodel_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentmodel",
            name="file_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("uploading", "Uploading"),
                    ("uploaded", "Uploaded"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="experimentmodel",
            name="received_chunks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="experimentmodel",
            name="total_chunks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experimentmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("uploading", "Uploading"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("error", "Error"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterModelTable(
            name="experimentmodel",
            table=None,
        ),
    ]
