# Generated by Django 5.1.3 on 2025-03-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0002_remove_gatemodel_x_axis_remove_gatemodel_x_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatemodel",
            name="gate_coordinates",
            field=models.JSONField(default={}),
        ),
    ]
