# Generated by Django 5.1.3 on 2025-03-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0003_alter_gatemodel_gate_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatemodel",
            name="gate_coordinates",
            field=models.JSONField(default=dict),
        ),
    ]
