# Generated by Django 5.0.2 on 2024-03-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0003_experimentmodel_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentmodel",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="experimentmodel",
            name="type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
