# Generated by Django 5.2.1 on 2026-06-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0004_experimentmodel_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedatamodel",
            name="fcs_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="filedatamodel",
            name="last_accessed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="filedatamodel",
            name="parquet_path",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="filedatamodel",
            name="data_set",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
