# Generated by Django 5.0.2 on 2024-04-01 01:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0005_alter_experimentmodel_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentmodel",
            name="values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
    ]
