# Generated by Django 5.2.1 on 2026-08-19 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0006_experimentmodel_zip_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentmodel",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="experimentmodel",
            unique_together={("title", "created_by")},
        ),
    ]
