# Generated by Django 5.0.2 on 2024-06-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0007_filemodel_filedatamodel_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemodel",
            name="file",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="filemodel",
            name="file_name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="filedatamodel",
            name="file",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_data",
                to="fcs_parser.filemodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="filemodel",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
