# Generated by Django 5.2.1 on 2026-08-19 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_auth_provider"),
        ("fcs_parser", "0007_alter_experimentmodel_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="experimentmodel",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="experimentmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("title", "created_by", "organization"),
                name="unique_title_per_user_and_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="experimentmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", True)),
                fields=("title", "created_by"),
                name="unique_title_per_user_personal",
            ),
        ),
    ]
