# Generated by Django 5.0.2 on 2024-06-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0008_filemodel_file_filemodel_file_name_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="filemodel",
            table="experiment_files",
        ),
    ]
