# Generated by Django 5.2.1 on 2026-09-13 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcs_parser', '0009_filedatamodel_active_filedatamodel_deactivated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filedatamodel',
            name='source_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.CreateModel(
            name='SubsampleModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('source_path', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subsamples', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsamples', to='fcs_parser.experimentmodel')),
            ],
            options={
                'db_table': 'subsamples',
            },
        ),
        migrations.AddField(
            model_name='filedatamodel',
            name='subsample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='fcs_parser.subsamplemodel'),
        ),
        migrations.AddConstraint(
            model_name='filedatamodel',
            constraint=models.UniqueConstraint(condition=models.Q(('source_path', ''), _negated=True), fields=('experiment', 'source_path'), name='unique_source_path_per_experiment'),
        ),
        migrations.AddConstraint(
            model_name='subsamplemodel',
            constraint=models.UniqueConstraint(fields=('experiment', 'name'), name='unique_subsample_name_per_experiment'),
        ),
    ]
