# Generated by Django 5.0.2 on 2024-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0010_filemodel_experiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentmodel",
            name="error_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="experimentmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("error", "Error"),
                ],
                default="processing",
                max_length=50,
            ),
        ),
    ]
