# Generated by Django 5.0.2 on 2024-06-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0013_alter_experimentmodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemodel",
            name="file",
            field=models.BinaryField(null=True),
        ),
    ]
