# Generated by Django 5.2.1 on 2026-09-13 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_auth_provider'),
        ('fcs_parser', '0014_filemodel_fk_chunks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='experimentmodel',
            name='unique_title_per_user_and_org',
        ),
        migrations.RemoveConstraint(
            model_name='experimentmodel',
            name='unique_title_per_user_personal',
        ),
        migrations.AddConstraint(
            model_name='experimentmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('organization__isnull', False)), fields=('title', 'created_by', 'organization'), name='unique_title_per_user_and_org'),
        ),
        migrations.AddConstraint(
            model_name='experimentmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('organization__isnull', True)), fields=('title', 'created_by'), name='unique_title_per_user_personal'),
        ),
    ]
