# Generated by Django 5.0.2 on 2024-07-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0014_alter_filemodel_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemodel",
            name="file",
            field=models.FileField(null=True, upload_to="storage"),
        ),
    ]
