# Generated by Django 5.2.1 on 2026-09-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fcs_parser",
            "0015_remove_experimentmodel_unique_title_per_user_and_org_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subsamplemodel",
            name="control_channel",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="subsamplemodel",
            name="control_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unstained", "Negativo (unstained)"),
                    ("single_stain", "Single stain"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
