# Generated by Django 5.0.4 on 2024-07-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0015_alter_filemodel_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="GateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("x_min", models.FloatField()),
                ("x_max", models.FloatField()),
                ("y_min", models.FloatField()),
                ("y_max", models.FloatField()),
                ("x_axis", models.CharField()),
                ("y_axis", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates",
                        to="fcs_parser.experimentmodel",
                    ),
                ),
                (
                    "file_data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates",
                        to="fcs_parser.filedatamodel",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="fcs_parser.gatemodel",
                    ),
                ),
            ],
        ),
    ]
