# Generated by Django 5.2.1 on 2026-09-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0016_subsamplemodel_control_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentmodel",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
