# Generated by Django 5.0.4 on 2024-07-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0017_create_notify_trigger"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gatemodel",
            table="gate",
        ),
    ]
