# Generated by Django 5.2.16 on 2026-09-18 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# BE-34: labels de sistema — semântica estável referenciada por
# `system_key` no código (sugestões, controles, consumidores futuros).
SYSTEM_LABELS = [
    # (system_key, name, category, color)
    ("unstained", "Negativo (unstained)", "control", "#f59e0b"),
    ("fmo", "FMO", "control", "#8b5cf6"),
    ("isotype", "Isotípico", "control", "#06b6d4"),
    ("single_stain", "Single stain", "control", "#ec4899"),
    ("biological_ref", "Referência biológica", "control", "#10b981"),
    ("beads", "Beads", "control", "#64748b"),
]


def seed_system_labels(apps, schema_editor):
    SampleLabel = apps.get_model("fcs_parser", "SampleLabelModel")
    for system_key, name, category, color in SYSTEM_LABELS:
        SampleLabel.objects.get_or_create(
            system_key=system_key,
            defaults={
                "name": name,
                "name_normalized": " ".join(name.split()).lower(),
                "category": category,
                "color": color,
                "scope": "system",
                "scope_key": "system",
            },
        )


def unseed_system_labels(apps, schema_editor):
    SampleLabel = apps.get_model("fcs_parser", "SampleLabelModel")
    SampleLabel.objects.filter(scope="system").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_merged_into"),
        ("fcs_parser", "0018_experimenttypemodel_experimentmodel_experiment_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleLabelModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("name_normalized", models.CharField(max_length=100)),
                (
                    "system_key",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("control", "Controle"), ("general", "Geral")],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(default="#6b7280", max_length=7)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("system", "Sistema"),
                            ("organization", "Organização"),
                            ("personal", "Pessoal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope_key", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sample_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_labels",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "db_table": "sample_labels",
            },
        ),
        migrations.CreateModel(
            name="FileLabelModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_file_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_labels",
                        to="fcs_parser.filedatamodel",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_links",
                        to="fcs_parser.samplelabelmodel",
                    ),
                ),
            ],
            options={
                "db_table": "file_labels",
            },
        ),
        migrations.AddField(
            model_name="filedatamodel",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="labeled_files",
                through="fcs_parser.FileLabelModel",
                to="fcs_parser.samplelabelmodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="samplelabelmodel",
            constraint=models.UniqueConstraint(
                fields=("scope_key", "name_normalized"),
                name="unique_label_name_per_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="filelabelmodel",
            constraint=models.UniqueConstraint(
                fields=("file_data", "label"), name="unique_label_per_file"
            ),
        ),
        migrations.RunPython(seed_system_labels, unseed_system_labels),
    ]
