# Generated by Django 5.2.16 on 2026-09-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0019_sampletagmodel_filetagmodel_filedatamodel_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsamplemodel",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="tagged_subsamples",
                to="fcs_parser.sampletagmodel",
            ),
        ),
    ]
