# Generated by Django 5.2.1 on 2026-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcs_parser", "0020_subsamplemodel_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedatamodel",
            name="plot_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
