# Generated by Django 5.1.3 on 2025-03-25 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fcs_parser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("dashboard_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to="fcs_parser.experimentmodel",
                    ),
                ),
                (
                    "file_data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to="fcs_parser.filedatamodel",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard",
            },
        ),
        migrations.CreateModel(
            name="GateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("gate_coordinates", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates",
                        to="analytics.dashboardmodel",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates",
                        to="fcs_parser.experimentmodel",
                    ),
                ),
                (
                    "file_data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gates",
                        to="fcs_parser.filedatamodel",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="analytics.gatemodel",
                    ),
                ),
            ],
            options={
                "db_table": "gate",
            },
        ),
        migrations.AddIndex(
            model_name="dashboardmodel",
            index=models.Index(
                fields=["dashboard_data", "name"], name="dashboard_dashboa_25d62e_idx"
            ),
        ),
    ]
