# Generated by Django 5.2.1 on 2025-05-30 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("fcs_parser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_result", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "analysis_result",
            },
        ),
        migrations.RemoveIndex(
            model_name="dashboardmodel",
            name="dashboard_dashboa_25d62e_idx",
        ),
        migrations.RenameField(
            model_name="dashboardmodel",
            old_name="dashboard_data",
            new_name="dashboard_config",
        ),
        migrations.RemoveField(
            model_name="dashboardmodel",
            name="experiment",
        ),
        migrations.RemoveField(
            model_name="dashboardmodel",
            name="file_data",
        ),
        migrations.AddIndex(
            model_name="dashboardmodel",
            index=models.Index(
                fields=["dashboard_config", "name"], name="dashboard_dashboa_ef3300_idx"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="file_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fcs_parser.filedatamodel",
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="gate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.gatemodel"
            ),
        ),
    ]
