# Generated by Django 5.2.1 on 2025-05-31 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_analysisresult_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisresult",
            name="file_data",
        ),
        migrations.RemoveField(
            model_name="analysisresult",
            name="id",
        ),
        migrations.RemoveField(
            model_name="gatemodel",
            name="experiment",
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="gate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="analytics.gatemodel",
            ),
        ),
    ]
