# Generated by Django 5.2.1 on 2025-07-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_remove_analysisresult_file_data_and_more"),
        ("fcs_parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardmodel",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="gatemodel",
            name="name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="gatemodel",
            unique_together={("name", "file_data")},
        ),
    ]
