# Generated by Django 5.2.1 on 2025-07-25 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_dashboardmodel_name_alter_gatemodel_name_and_more"),
        ("fcs_parser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dashboardmodel",
            name="dashboard_dashboa_ef3300_idx",
        ),
        migrations.AddField(
            model_name="dashboardmodel",
            name="file_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboards",
                to="fcs_parser.filedatamodel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dashboardmodel",
            unique_together={("name", "file_data")},
        ),
    ]
