# Generated by Django 5.2.1 on 2025-07-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0005_remove_dashboardmodel_dashboard_dashboa_ef3300_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisresult",
            name="gate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="analysis_result",
                serialize=False,
                to="analytics.gatemodel",
            ),
        ),
    ]
