# Generated by Django 5.2.1 on 2026-06-17 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_remove_unique_together_add_tree_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatemodel",
            name="copied_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="analytics.gatemodel",
            ),
        ),
    ]
