# Generated by Django 5.2.1 on 2026-06-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0008_add_copied_from_to_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatemodel",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
