# Generated by Django 5.2.1 on 2026-09-15 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0011_gatemodel_created_by"),
        (
            "fcs_parser",
            "0015_remove_experimentmodel_unique_title_per_user_and_org_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("gate", "Gate"),
                            ("subsample", "Subsample"),
                            ("file", "Amostra"),
                            ("experiment", "Experimento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.BigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Criação"),
                            ("update_geometry", "Geometria"),
                            ("rename", "Renomear"),
                            ("recolor", "Cor"),
                            ("apply", "Aplicar em amostras"),
                            ("delete", "Excluir"),
                            ("disable", "Desativar"),
                            ("enable", "Reativar"),
                            ("move_subsample", "Mover de subsample"),
                            ("revert", "Reversão"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("file", "Amostra"),
                            ("subsample", "Subsample"),
                            ("experiment", "Experimento"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("payload_before", models.JSONField(blank=True, default=dict)),
                ("payload_after", models.JSONField(blank=True, default=dict)),
                ("affected_ids", models.JSONField(blank=True, default=list)),
                ("summary", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_revisions",
                        to="fcs_parser.experimentmodel",
                    ),
                ),
                (
                    "reverts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverted_by",
                        to="analytics.analysisrevision",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analysis_revision",
                "indexes": [
                    models.Index(
                        fields=["experiment", "-created_at"],
                        name="analysis_re_experim_cd569b_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="analysis_re_target__2d9e7f_idx",
                    ),
                ],
            },
        ),
    ]
