# Generated by Django 5.2.1 on 2026-09-15 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0012_analysisrevision"),
        (
            "fcs_parser",
            "0015_remove_experimentmodel_unique_title_per_user_and_org_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrevision",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Criação"),
                    ("update_geometry", "Geometria"),
                    ("rename", "Renomear"),
                    ("recolor", "Cor"),
                    ("apply", "Aplicar em amostras"),
                    ("delete", "Excluir"),
                    ("disable", "Desativar"),
                    ("enable", "Reativar"),
                    ("move_subsample", "Mover de subsample"),
                    ("revert", "Reversão"),
                    ("restore", "Restauração de ponto"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AnalysisCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_checkpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="fcs_parser.experimentmodel",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkpoints",
                        to="analytics.analysisrevision",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_checkpoint",
                "indexes": [
                    models.Index(
                        fields=["experiment", "-created_at"],
                        name="analysis_ch_experim_9a55c2_idx",
                    )
                ],
            },
        ),
    ]
