# Generated by Django 5.2.1 on 2026-09-16 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0013_alter_analysisrevision_action_analysischeckpoint"),
        ("fcs_parser", "0016_subsamplemodel_control_channel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrevision",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Criação"),
                    ("update_geometry", "Geometria"),
                    ("rename", "Renomear"),
                    ("recolor", "Cor"),
                    ("apply", "Aplicar em amostras"),
                    ("delete", "Excluir"),
                    ("disable", "Desativar"),
                    ("enable", "Reativar"),
                    ("move_subsample", "Mover de subsample"),
                    ("revert", "Reversão"),
                    ("restore", "Restauração de ponto"),
                    ("compensation_apply", "Aplicar compensação"),
                    ("compensation_remove", "Remover compensação"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="analysisrevision",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("gate", "Gate"),
                    ("subsample", "Subsample"),
                    ("file", "Amostra"),
                    ("experiment", "Experimento"),
                    ("compensation", "Compensação"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CompensationMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=256)),
                ("channels", models.JSONField(default=list)),
                ("matrix", models.JSONField(default=list)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("fcs_header", "Embutida no FCS"),
                            ("computed", "Calculada de controles"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_applied", models.BooleanField(default=False)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_compensations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensations",
                        to="fcs_parser.experimentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "compensation_matrix",
                "indexes": [
                    models.Index(
                        fields=["experiment", "-created_at"],
                        name="compensatio_experim_151964_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_applied", True)),
                        fields=("experiment",),
                        name="unique_applied_compensation_per_experiment",
                    )
                ],
            },
        ),
    ]
