# Generated by Django 5.2.1 on 2026-09-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0014_alter_analysisrevision_action_and_more"),
        ("fcs_parser", "0016_subsamplemodel_control_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrevision",
            name="file_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_revisions",
                to="fcs_parser.filedatamodel",
            ),
        ),
    ]
