# Generated by Django 5.2.1 on 2026-09-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0015_analysisrevision_file_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrevision",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Criação"),
                    ("update_geometry", "Geometria"),
                    ("rename", "Renomear"),
                    ("recolor", "Cor"),
                    ("apply", "Aplicar em amostras"),
                    ("delete", "Excluir"),
                    ("disable", "Desativar"),
                    ("enable", "Reativar"),
                    ("move_subsample", "Mover de subsample"),
                    ("revert", "Reversão"),
                    ("restore", "Restauração de ponto"),
                    ("compensation_apply", "Aplicar compensação"),
                    ("compensation_remove", "Remover compensação"),
                    ("derive", "Derivação de análise"),
                ],
                max_length=20,
            ),
        ),
    ]
