# Generated by Django 5.2.1 on 2026-09-16 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_main_branch(apps, schema_editor):
    """Cria a branch `main` por experimento e ancora gates/revisões nela."""
    AnalysisBranch = apps.get_model("analytics", "AnalysisBranch")
    GateModel = apps.get_model("analytics", "GateModel")
    AnalysisRevision = apps.get_model("analytics", "AnalysisRevision")
    ExperimentModel = apps.get_model("fcs_parser", "ExperimentModel")

    for exp in ExperimentModel.objects.all():
        main, _ = AnalysisBranch.objects.get_or_create(
            experiment_id=exp.id, is_main=True, defaults={"name": "main"}
        )
        GateModel.objects.filter(
            file_data__experiment_id=exp.id, branch__isnull=True
        ).update(branch_id=main.id)
        AnalysisRevision.objects.filter(
            experiment_id=exp.id, branch__isnull=True
        ).update(branch_id=main.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0016_alter_analysisrevision_action"),
        ("fcs_parser", "0016_subsamplemodel_control_channel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("is_main", models.BooleanField(default=False)),
                ("fork_snapshot", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analysis_branch",
            },
        ),
        migrations.RemoveConstraint(
            model_name="gatemodel",
            name="unique_gate_name_root_level",
        ),
        migrations.AddField(
            model_name="gatemodel",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forked_copies",
                to="analytics.gatemodel",
            ),
        ),
        migrations.AlterField(
            model_name="analysisrevision",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Criação"),
                    ("update_geometry", "Geometria"),
                    ("rename", "Renomear"),
                    ("recolor", "Cor"),
                    ("apply", "Aplicar em amostras"),
                    ("delete", "Excluir"),
                    ("disable", "Desativar"),
                    ("enable", "Reativar"),
                    ("move_subsample", "Mover de subsample"),
                    ("revert", "Reversão"),
                    ("restore", "Restauração de ponto"),
                    ("compensation_apply", "Aplicar compensação"),
                    ("compensation_remove", "Remover compensação"),
                    ("derive", "Derivação de análise"),
                    ("fork", "Criação de branch"),
                    ("merge", "Merge de branch"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="analysisrevision",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("gate", "Gate"),
                    ("subsample", "Subsample"),
                    ("file", "Amostra"),
                    ("experiment", "Experimento"),
                    ("compensation", "Compensação"),
                    ("branch", "Branch"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="analysisbranch",
            name="base_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_branches",
                to="analytics.analysisbranch",
            ),
        ),
        migrations.AddField(
            model_name="analysisbranch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_branches_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="analysisbranch",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_branches",
                to="fcs_parser.experimentmodel",
            ),
        ),
        migrations.AddField(
            model_name="analysisrevision",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revisions",
                to="analytics.analysisbranch",
            ),
        ),
        migrations.AddField(
            model_name="gatemodel",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gates",
                to="analytics.analysisbranch",
            ),
        ),
        migrations.RunPython(backfill_main_branch, noop_reverse),
        migrations.AlterField(
            model_name="gatemodel",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gates",
                to="analytics.analysisbranch",
            ),
        ),
        migrations.AddConstraint(
            model_name="gatemodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name", "file_data", "branch"),
                name="unique_gate_name_root_level",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisbranch",
            index=models.Index(
                fields=["experiment"], name="analysis_br_experim_53372b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisbranch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=["experiment", "name"],
                name="unique_branch_name_per_experiment",
            ),
        ),
    ]
