# Generated by Django 5.2.1 on 2026-09-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0018_alter_analysisrevision_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationmatrix",
            name="derived_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adjustments",
                to="analytics.compensationmatrix",
            ),
        ),
    ]
