# Generated by Django 5.2.1 on 2026-09-29 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0019_compensationmatrix_derived_from"),
        ("fcs_parser", "0021_filedatamodel_plot_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("stats_bar", "Barras agrupadas"),
                            ("stats_strip", "Pontos individuais"),
                            ("distribution", "Distribuição sobreposta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("spec", models.JSONField(default=dict)),
                ("result_cache", models.JSONField(blank=True, null=True)),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_figures",
                        to="analytics.analysisbranch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_figures_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_figures",
                        to="fcs_parser.experimentmodel",
                    ),
                ),
                (
                    "result_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_figures",
                        to="analytics.analysisrevision",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_figure",
                "indexes": [
                    models.Index(
                        fields=["experiment", "-updated_at"],
                        name="analysis_fi_experim_70b682_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("experiment", "name"),
                        name="unique_figure_name_per_experiment",
                    )
                ],
            },
        ),
    ]
