# Generated by Django 5.2.17 on 2026-10-06 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_analysisfigure'),
        ('fcs_parser', '0021_filedatamodel_plot_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysischeckpoint',
            name='origin',
            field=models.CharField(choices=[('user', 'Usuário'), ('juvia', 'Juvia')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisrevision',
            name='origin',
            field=models.CharField(choices=[('user', 'Usuário'), ('juvia', 'Juvia')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='gatemodel',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('cluster', 'Clusterização')], default='cluster', max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('transform', models.CharField(default='linear', max_length=20)),
                ('channels', models.JSONField(default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Na fila'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro (retentando)'), ('quarantine', 'Quarentena')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='fcs_parser.experimentmodel')),
                ('file_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='fcs_parser.filedatamodel')),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to='analytics.gatemodel')),
                ('subsample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_jobs', to='fcs_parser.subsamplemodel')),
            ],
            options={
                'db_table': 'analysis_job',
                'indexes': [models.Index(fields=['status', 'created_at'], name='analysis_jo_status_333d16_idx'), models.Index(fields=['experiment', '-created_at'], name='analysis_jo_experim_e644f9_idx')],
            },
        ),
    ]
