# Generated by Django 5.2.1 on 2026-08-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_membership_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("local", "Local"),
                    ("google", "Google"),
                    ("microsoft", "Microsoft"),
                ],
                default="local",
                help_text="Provedor usado para autenticação deste usuário.",
                max_length=20,
            ),
        ),
    ]
