# Generated by Django 5.2.16 on 2026-09-17 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_authevent_socialaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                help_text="Conta canônica que absorveu esta conta num merge (BE-30).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
