from django.urls import path

from .views import (
    DisableFileDataView,
    EnableFileDataView,
    ExperimentCompensationApplyView,
    ExperimentCompensationComputeView,
    ExperimentCompensationFromHeaderView,
    ExperimentCompensationListView,
    ExperimentCompensationPreviewView,
    ExperimentCompensationRemoveView,
    ExperimentCompleteView,
    ExperimentCopyView,
    ExperimentDeriveAnalysisView,
    ExperimentDownloadView,
    ExperimentEmbeddedCompensationView,
    ExperimentFileChunkView,
    ExperimentFileCompleteView,
    ExperimentFileInitView,
    ExperimentInitView,
    ExperimentListView,
    ExperimentPreviewView,
    ExperimentRestoreView,
    ExperimentTypeListCreateView,
    FileDensityView,
    FileHashCheckView,
    FileHeadersView,
    FileTagsView,
    FileStatsView,
    FileSubsampleView,
    GetExperimentFiles,
    TagDetailView,
    TagListCreateView,
    ListFileParams,
    ProcessFileDataView,
    RecomputeFileDataView,
    RetrieveDeleteExperimentView,
    SubsampleDetailView,
    SubsampleListCreateView,
    UploadChunkView,
)

app_name = "fcs_parser"

urlpatterns = [
    path("init/", ExperimentInitView.as_view()),
    path("upload-chunk/", UploadChunkView.as_view()),
    path("complete/", ExperimentCompleteView.as_view()),
    path("check-hash/", FileHashCheckView.as_view()),
    path("files/upload-chunk/", ExperimentFileChunkView.as_view()),
    path("files/complete/", ExperimentFileCompleteView.as_view()),
    path("<int:experiment_id>/files/init", ExperimentFileInitView.as_view()),
    path("<int:experiment_id>/download", ExperimentDownloadView.as_view()),
    path("<int:experiment_id>/copy", ExperimentCopyView.as_view()),
    path(
        "<int:experiment_id>/derive-analysis",
        ExperimentDeriveAnalysisView.as_view(),
    ),
    path("<int:experiment_id>/preview", ExperimentPreviewView.as_view()),
    path(
        "<int:experiment_id>/compensations/embedded",
        ExperimentEmbeddedCompensationView.as_view(),
    ),
    path(
        "<int:experiment_id>/compensations/",
        ExperimentCompensationListView.as_view(),
    ),
    path(
        "<int:experiment_id>/compensations/from-header",
        ExperimentCompensationFromHeaderView.as_view(),
    ),
    path(
        "<int:experiment_id>/compensations/compute",
        ExperimentCompensationComputeView.as_view(),
    ),
    path(
        "<int:experiment_id>/compensations/preview",
        ExperimentCompensationPreviewView.as_view(),
    ),
    path(
        "<int:experiment_id>/compensations/<int:matrix_id>/apply",
        ExperimentCompensationApplyView.as_view(),
    ),
    path(
        "<int:experiment_id>/compensations/remove",
        ExperimentCompensationRemoveView.as_view(),
    ),
    path("<int:experiment_id>/restore", ExperimentRestoreView.as_view()),
    # `types/` e `tags/` precisam vir antes de `<str:experiment_id>/`
    # para não ser capturados como id de experimento.
    path("types/", ExperimentTypeListCreateView.as_view()),
    path("tags/", TagListCreateView.as_view()),
    path("tags/<int:pk>/", TagDetailView.as_view()),
    path("list/data/<str:experiment_id>/", GetExperimentFiles.as_view()),
    path("file/<str:file_id>/list", ListFileParams.as_view()),
    path("file/<int:file_id>/density", FileDensityView.as_view()),
    path("file/<int:file_id>/recompute", RecomputeFileDataView.as_view()),
    path("file/<int:file_id>/stats", FileStatsView.as_view()),
    path("file/<int:file_id>/headers", FileHeadersView.as_view()),
    path("file/<int:file_id>/disable", DisableFileDataView.as_view()),
    path("file/<int:file_id>/enable", EnableFileDataView.as_view()),
    path(
        "file/<int:file_id>/subsample",
        FileSubsampleView.as_view(),
        name="file_subsample",
    ),
    path(
        "file/<int:file_id>/tags",
        FileTagsView.as_view(),
        name="file_tags",
    ),
    path(
        "<int:experiment_id>/subsamples/",
        SubsampleListCreateView.as_view(),
        name="subsample_list_create",
    ),
    path(
        "<int:experiment_id>/subsamples/<int:pk>/",
        SubsampleDetailView.as_view(),
        name="subsample_detail",
    ),
    path("<str:experiment_id>/", RetrieveDeleteExperimentView.as_view()),
    path("file/<int:file_id>/process", ProcessFileDataView.as_view()),
    path("", ExperimentListView.as_view()),
]
